DROP TABLE IF EXISTS "student";
DROP TABLE IF EXISTS "item";
DROP TABLE IF EXISTS "checkout";
DROP TABLE IF EXISTS "checkin";

CREATE TABLE IF NOT EXISTS "student" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "item" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	TEXT NOT NULL,
	"type"	TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "checkout" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"student_id" INTEGER NOT NULL,
	"item_id"	INTEGER NOT NULL,
	"dateOut"TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(student_id) REFERENCES student(id) ON DELETE CASCADE,
	FOREIGN KEY(item_id) REFERENCES item(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "checkin" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"student_id" INTEGER NOT NULL,
	"item_id"	INTEGER NOT NULL,
	"dateOut"TIMESTAMP NOT NULL,
	"dateIn"TIMESTAMP NOT NULL,
	FOREIGN KEY(student_id) REFERENCES student(id) ON DELETE CASCADE,
	FOREIGN KEY(item_id) REFERENCES item(id) ON DELETE CASCADE
);


INSERT INTO "student"(name) VALUES("Luis Mata"),("Justin Weigand"),("Logan Mccleod");
INSERT INTO "item"(name, type) VALUES("80D", "Camera"),("Sony A7", "Camera");
INSERT INTO "checkout"(student_id, item_id) VALUES(1,1);