DROP TABLE IF EXISTS "students";
DROP TABLE IF EXISTS "items";
DROP TABLE IF EXISTS "checkout";

CREATE TABLE IF NOT EXISTS "student" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "item" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"item"	TEXT NOT NULL,
	"type"	TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "checkout" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"student_id" INTEGER NOT NULL,
	"item_id"	INTEGER NOT NULL,
	"dateOut"TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(student_id) REFERENCES student(id) ON DELETE CASCADE,
	FOREIGN KEY(item_id) REFERENCES item(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "checkin" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"student_id"	INTEGER NOT NULL,
	"item_id"		INTEGER NOT NULL,
	"dateIn"TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(student_id) REFERENCES student(id) ON DELETE CASCADE,
	FOREIGN KEY(item_id) REFERENCES item(id) ON DELETE CASCADE
);